# Generated by Django 4.0 on 2021-12-19 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fake_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='name')),
                ('email', models.CharField(max_length=50, verbose_name='email')),
                ('password', models.CharField(max_length=30, verbose_name='password')),
            ],
        ),
    ]
